
USE QLGV

-- CAU 9:
CREATE TRIGGER TRG_LOP_INSERT ON LOP
FOR INSERT, UPDATE
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM INSERTED I, HOCVIEN HV
	WHERE I.TRGLOP = HV.MAHV AND I.MALOP = HV.MALOP)
	BEGIN
		PRINT ('LOI.Lop truong cua mot lop phai la hoc vien cua lop do')
		ROLLBACK TRANSACTION
	END
END

CREATE TRIGGER TRG_DELETE_HV ON HOCVIEN
FOR DELETE
AS
BEGIN
	IF EXISTS (SELECT * FROM DELETED D, INSERTED I, LOP L 
	WHERE D.MAHV = L.TRGLOP AND D.MALOP = L.MALOP)
	BEGIN
		PRINT ('KHONG XOA DUOC. Do hoc vien hien tai dang la truong lop')
		ROLLBACK TRANSACTION
	END
END

-- CAU 11:
ALTER TABLE HOCVIEN ADD CONSTRAINT CHECK_TUOI CHECK (YEAR(GETDATE()) - YEAR(NGSINH) >= 18)

-- CAU 12:
ALTER TABLE GIANGDAY ADD CONSTRAINT CHECK_GIANGDAY CHECK (TUNGAY < DENNGAY)

-- CAU 13:
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHECK_TUOILAM CHECK (YEAR(NGVL) - YEAR(NGSINH) >= 22)

-- CAU 14:
ALTER TABLE MONHOC ADD CONSTRAINT CHECK_TINCHI CHECK ((TCLT - TCTH) <= 3)
--CAU 16:
CREATE TRIGGER TRG_GD_INSERT ON GIANGDAY
FOR INSERT
AS 
BEGIN
	DECLARE @SOMON INT,@MAMH VARCHAR(10),@MALOP CHAR(3)
	SELECT @SOMON=COUNT(MAMH) 
	FROM deleted 
	GROUP BY MALOP,HOCKY,NAM
	IF(@SOMON=3)
		PRINT('KHONG INSERT DUOC Do vi pham rang buoc toan ven.')
		ROLLBACK TRANSACTION
END
--CAU 17:
--INSERT HOCVIEN
CREATE TRIGGER TRG_HV_INSERT ON HOCVIEN
FOR INSERT
AS
BEGIN
	DECLARE @MAHV CHAR(5),@MALOP CHAR(3),@SS INT
	SELECT @MAHV=A.MAHV,@MALOP=B.MALOP,@SS=B.SISO
	FROM deleted A, LOP B
	WHERE A.MALOP=B.MALOP

	UPDATE LOP
	SET SISO=@SS+1
	WHERE MALOP=@MALOP
	PRINT('INSERT HOCVIEN THANH CONG.')
END
--DELETE HOCVIEN
CREATE TRIGGER TRG_HV_DELETE ON HOCVIEN
FOR DELETE
AS
BEGIN
	DECLARE @MAHV CHAR(5),@MALOP CHAR(3),@SS INT
	SELECT @MAHV=A.MAHV,@MALOP=B.MALOP,@SS=B.SISO
	FROM deleted A, LOP B
	WHERE A.MALOP=B.MALOP

	UPDATE LOP
	SET SISO=@SS-1
	WHERE MALOP=@MALOP
	PRINT('DELETED HOCVIEN THANH CONG.')
END
--UPDATE MALOP
CREATE TRIGGER TRG_HV_UPDATE_ML ON HOCVIEN
FOR UPDATE
AS
BEGIN
	DECLARE @MAHV CHAR(5),@MALOP_MOI CHAR(3),@SS INT,@MALOP_CU CHAR(3)
	SELECT @MAHV=A.MAHV,@MALOP_CU=B.MALOP
	FROM deleted A, LOP B
	WHERE A.MALOP=B.MALOP

	SELECT @MAHV=A.MAHV,@MALOP_MOI=B.MALOP
	FROM inserted A, LOP B
	WHERE A.MALOP=B.MALOP

	UPDATE LOP
	SET SISO=SISO-1
	WHERE MALOP=@MALOP_CU
	PRINT('DELETE HOCVIEN KHOI LOP CU THANH CONG.')

	UPDATE LOP
	SET  SISO=SISO+1
	WHERE MALOP=@MALOP_MOI
	PRINT('INSERT HOCVIEN VAO LOP MOI THANH CONG.')
END

--UPDATE SISO
CREATE TRIGGER TRG_UPDATE_SS ON LOP
FOR UPDATE
AS
BEGIN
	DECLARE @MALOP CHAR(3),@SS_MOI INT,@SS_CU INT
	SELECT @SS_CU=COUNT(B.MAHV)
	FROM deleted A, HOCVIEN B
	WHERE A.MALOP=B.MALOP
	GROUP BY B.MALOP

	SELECT @SS_MOI=SISO FROM inserted
	IF(@SS_CU!=@SS_MOI)
		BEGIN
		PRINT('KHONG UPDATE DUOC.')
		ROLLBACK TRANSACTION
		END
	ELSE
		BEGIN
		PRINT('UPDATE THANH CONG.')
		END
END